### ISSUE TITLE
Hard drive consumed from inventory but no recipe choice granted

### ISSUE THREAD

**Issue by Razoroth** [budak7273/ShortenHardDriveResearch#1]
EDIT: Disregard. After a few minutes, reopening the MAM screen gave me the recipe choice.

**Comment by budak7273** [comment]
Make sure you have the mod installed on both the server and client side. It sounds like the server and client disagreed on how long the research was supposed to take.

**Comment by Razoroth** [comment]
I installed with the mod manager, other mods that install to both sides installed correctly and are working. Not really sure what happened tbh. It definitely wasn't 10 minutes, but it took longer than 3 seconds for it to work. But at least it didn't waste a hard drive 😁
